services:
  # Bases de datos para cada microservicio
  mysql-auth:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: auth_db
    ports:
      - "3307:3306"
    networks:
      - clinic-network
    volumes:
      - mysql-auth:/var/lib/mysql

  mysql-pacientes:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: pacientes_db
    ports:
      - "3309:3306"
    networks:
      - clinic-network
    volumes:
      - mysql-pacientes:/var/lib/mysql
      
  mysql-persona:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: persona-service
    ports:
      - "3310:3306"          # Cambié puerto para evitar conflicto con pacientes
    networks:
      - clinic-network
    volumes:
      - mysql-persona:/var/lib/mysql  # Nombre de volumen corregido

  mysql-medico:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ms-medico
    ports:
      - "3308:3306"
    networks:
      - clinic-network
    volumes:
      - mysql-medico:/var/lib/mysql

  # Infraestructura
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    image: eureka-server:latest
    ports:
      - "8761:8761"
    networks:
      - clinic-network

  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    image: config-server:latest
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server
    networks:
      - clinic-network

  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    image: gateway-service:latest
    ports:
      - "8089:8080"
    depends_on:
      - eureka-server
      - config-server
    networks:
      - clinic-network
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

  # Microservicios
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    image: auth-service:latest
    ports:
      - "8081:8081"
    depends_on:
      - mysql-auth
      - config-server
      - eureka-server
    networks:
      - clinic-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-auth:3306/auth_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

  pacientes-service:
    build:
      context: ./pacientes-service
      dockerfile: Dockerfile
    image: pacientes-service:latest
    ports:
      - "8086:8086"
    depends_on:
      - mysql-pacientes
      - config-server
    networks:
      - clinic-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-pacientes:3306/pacientes_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456

  doctor-service:
    build:
      context: ./doctor-service    # Revisa si es minúscula o mayúscula en tu proyecto
      dockerfile: Dockerfile
    image: doctor-service:latest
    ports:
      - "8087:8087"
    depends_on:
      - mysql-medico
      - config-server
    networks:
      - clinic-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-medico:3306/ms-medico
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - clinic-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - clinic-network

networks:
  clinic-network:
    driver: bridge

volumes:
  mysql-auth:
  mysql-pacientes:
  mysql-persona:
  mysql-medico:
