server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Andre-Acosta2022/ConfigRepo.git
          force-pull: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/



management:
  endpoints:
    web:
      exposure:
        include: "*"

