spring:
  application:
    name: config-server
  cloud:
    config:


  eureka:
    client:
      service-url:
        defaultZone: http://eureka-server:8761/eureka/


  management:
    endpoints:
      web:
        exposure:
          include: health,info

server:
  port: 8888
